# Generated by Django 3.2.5 on 2021-07-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='catego', to='theblog.category'),
        ),
    ]
