# Generated by Django 3.2.5 on 2021-07-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20210718_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
